---
title       : Temp Converter
subtitle    : Temperature Conversion
author      : Huihui Duan
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Convert Fahrenheit & Celsius

Input 1: Degree Quantity
```{r, echo = TRUE}
(dq = 0)
```
Input 2: From Fahrenheit or Celsius
```{r, echo = TRUE}
(cf = "Celsius")
```

--- .class #id 

## Copied

Copied from the input: 

Result: 

You entered: 
```{r, echo = TRUE}
paste(dq, cf)
```

---
## Temp Converter to Fahrenheit

was converted to:
```{r, echo = TRUE}
paste(format(round(dq * 9 / 5 + 32, 2), nsmall = 2), "Fahrenheit")
```

---
## From Fahrenheit to Celsius
Input 1: Degree Quantity
```{r, echo = FALSE}
(dq = 0)
```
Input 2: From Fahrenheit or Celsius
```{r, echo = FALSE}
(cf = "Fahrenheit")
```

You entered: 
```{r, echo = FALSE}
paste(dq, cf)
```

was converted to:
```{r, echo = FALSE}
paste(format(round((dq - 32) * 5 / 9, 2), nsmall = 2), "Celsius")

```


